-- Clear existing personas
TRUNCATE TABLE public.personas CASCADE;

-- Insert new Personas (Indian Context - 100+ Entries with Emoji Avatars)
INSERT INTO public.personas (name, age, gender, bio, location, vibes, photos)
VALUES
    -- Female Personas (55 entries)
    ('Aisha', 24, 'Female', 'Fashion designer. Love street food and exploring hidden cafes.', 'Mumbai, India', ARRAY['Fashion', 'Foodie', 'Travel'], ARRAY['👗']),
    ('Priya', 26, 'Female', 'Software engineer. Weekend hiker and dancer. Debate code with me?', 'Bangalore, India', ARRAY['Techie', 'Dance', 'Nature'], ARRAY['👩‍💻']),
    ('Riya', 23, 'Female', 'Psychology student. Deep conversations and chai enthusiast.', 'Delhi, India', ARRAY['Deep Conversations', 'History', 'Chill'], ARRAY['🧘‍♀️']),
    ('Ananya', 25, 'Female', 'Digital marketer & yoga lover. Seeking peace in chaos.', 'Pune, India', ARRAY['Fitness', 'Spiritual', 'Creative'], ARRAY['🕉️']),
    ('Meera', 27, 'Female', 'Architect. Stories in old buildings. Painting & folk music.', 'Jaipur, India', ARRAY['Artistic', 'History', 'Music'], ARRAY['🏛️']),
    ('Kavya', 22, 'Female', 'Journalism student. Chasing stories and filter coffee.', 'Chennai, India', ARRAY['Intellectual', 'Writing', 'Coffee'], ARRAY['☕']),
    ('Sana', 24, 'Female', 'Baker. Cupcakes are my love language. Taste testers wanted.', 'Hyderabad, India', ARRAY['Foodie', 'Animals', 'Cooking'], ARRAY['🧁']),
    ('Diya', 28, 'Female', 'Lawyer by day, poet by night. Looking for a muse.', 'Gurgaon, India', ARRAY['Ambitious', 'Writing', 'Chill'], ARRAY['⚖️']),
    ('Ishita', 25, 'Female', 'Interior designer. OBSESSED with aesthetics. Let me rearrange your life.', 'Mumbai, India', ARRAY['Artistic', 'Creative', 'Ambition'], ARRAY['🛋️']),
    ('Neha', 29, 'Female', 'Doctor. Busy schedule but huge heart. Need someone who understands.', 'Delhi, India', ARRAY['Ambitious', 'Compassionate', 'Travel'], ARRAY['🩺']),
    ('Aditi', 21, 'Female', 'Art student. Museum dates and sketching in the park?', 'Kolkata, India', ARRAY['Artistic', 'Nature', 'Chill'], ARRAY['🎨']),
    ('Zoya', 26, 'Female', 'Marketing manager. Always on the go but down for spontaneous trips.', 'Bangalore, India', ARRAY['Travel', 'Ambition', 'Party'], ARRAY['✈️']),
    ('Naira', 23, 'Female', 'Dancer and content creator. Life is a performance.', 'Mumbai, India', ARRAY['Dance', 'Social Media', 'Creative'], ARRAY['💃']),
    ('Anika', 25, 'Female', 'UI/UX Designer. Pixel perfect life used to be the goal, now I want real.', 'Bangalore, India', ARRAY['Techie', 'Design', 'Chill'], ARRAY['📱']),
    ('Kiara', 24, 'Female', 'Event planner. I make magic happen. Looking for my own fairytale.', 'Delhi, India', ARRAY['Party', 'Organizer', 'Romantic'], ARRAY['💍']),
    ('Jhanvi', 27, 'Female', 'Data scientist. Numbers don''t lie, but people do. Change my mind.', 'Hyderabad, India', ARRAY['Techie', 'Intellectual', 'Gaming'], ARRAY['📊']),
    ('Myra', 22, 'Female', 'Music student. Violinist. I interpret the world through sound.', 'Chennai, India', ARRAY['Music', 'Artistic', 'Chill'], ARRAY['🎻']),
    ('Saanvi', 26, 'Female', 'Environmentalist. Saving the planet, one plant at a time. Join me?', 'Pune, India', ARRAY['Nature', 'Activism', 'Outdoors'], ARRAY['🌱']),
    ('Aanya', 23, 'Female', 'Blogger. Exploring the city''s best rooftops. Come along?', 'Mumbai, India', ARRAY['Writing', 'Social', 'Foodie'], ARRAY['✍️']),
    ('Pari', 25, 'Female', 'Kindergarten teacher. Patience of a saint, heart of a child.', 'Jaipur, India', ARRAY['Kids', 'Kind', 'Creative'], ARRAY['🧸']),
    ('Khushi', 21, 'Female', 'Student. Just here for good vibes and better memes.', 'Delhi, India', ARRAY['Humor', 'Chill', 'Students'], ARRAY['🎒']),
    ('Avni', 28, 'Female', 'Financial analyst. Stocks are up, looking for a partner to invest in.', 'Mumbai, India', ARRAY['Finance', 'Ambition', 'Travel'], ARRAY['📈']),
    ('Sara', 24, 'Female', 'Chef in training. Spicing things up. Can you handle the heat?', 'Goa, India', ARRAY['Cooking', 'Foodie', 'Beach'], ARRAY['🌶️']),
    ('Tanvi', 26, 'Female', 'Graphic Designer. Visual storyteller. Let''s create something beautiful.', 'Pune, India', ARRAY['Artistic', 'Creative', 'Techie'], ARRAY['🎭']),
    ('Ira', 29, 'Female', 'Professor. History buff. Let''s visit ancient ruins.', 'Varanasi, India', ARRAY['History', 'Intellectual', 'Travel'], ARRAY['📜']),
    ('Navya', 23, 'Female', 'App developer. Coding my way to your heart.', 'Bangalore, India', ARRAY['Techie', 'Coding', 'Gaming'], ARRAY['💻']),
    ('Trisha', 25, 'Female', 'HR specialist. I read people for a living. You''re interesting.', 'Gurgaon, India', ARRAY['People', 'Psychology', 'Chill'], ARRAY['🤝']),
    ('Vanya', 22, 'Female', 'Fashion blogger. OOTD is life. Be my photographer?', 'Mumbai, India', ARRAY['Fashion', 'Social Media', 'Photography'], ARRAY['🛍️']),
    ('Ahana', 27, 'Female', 'Dentist. Keep smiling, I''ll take care of the rest.', 'Delhi, India', ARRAY['Health', 'Kind', 'Chill'], ARRAY['🦷']),
    ('Chhavi', 24, 'Female', 'Artist. Canvas is my world. Be my subject.', 'Kolkata, India', ARRAY['Artistic', 'Painting', 'Deep Conversations'], ARRAY['🖼️']),
    ('Esha', 26, 'Female', 'Public Relations. Spinning stories. What''s yours?', 'Mumbai, India', ARRAY['Social', 'Communication', 'Party'], ARRAY['🎤']),
    ('Gauri', 23, 'Female', 'Social worker. Making a difference. Kindness matters.', 'Pune, India', ARRAY['Kind', 'Activism', 'Nature'], ARRAY['🤝']),
    ('Hamsini', 25, 'Female', 'Classical singer. Tradition meets modernity.', 'Chennai, India', ARRAY['Music', 'Tradition', 'Artistic'], ARRAY['🎶']),
    ('Inaya', 28, 'Female', 'Architect. Designing dreams. Let''s build a future.', 'Bangalore, India', ARRAY['Design', 'Ambitious', 'Creative'], ARRAY['🏢']),
    ('Jiya', 22, 'Female', 'Student. Coffee addict. Late night study sessions & jamming.', 'Delhi, India', ARRAY['Students', 'Coffee', 'Music'], ARRAY['🎧']),
    ('Kashish', 24, 'Female', 'Makeup artist. Enhancing beauty. You look good today.', 'Mumbai, India', ARRAY['Beauty', 'Artistic', 'Social'], ARRAY['💄']),
    ('Lavanya', 26, 'Female', 'Botanist. Plant mom. My apartment is a jungle.', 'Bangalore, India', ARRAY['Nature', 'Plants', 'Chill'], ARRAY['🌿']),
    ('Mahika', 23, 'Female', 'Dancer. Rhythm is everything. Teach me your moves.', 'Hyderabad, India', ARRAY['Dance', 'Fitness', 'Music'], ARRAY['🩰']),
    ('Naina', 25, 'Female', 'Photographer. Capturing moments. Let''s make memories.', 'Goa, India', ARRAY['Photography', 'Travel', 'Beach'], ARRAY['📷']),
    ('Ojasvini', 27, 'Female', 'Entrepreneur. Running my own show. Boss lady vibe.', 'Gurgaon, India', ARRAY['Entrepreneur', 'Ambition', 'Leadership'], ARRAY['💼']),
    ('Prisha', 24, 'Female', 'Yoga instructor. Balance is key. Namaste.', 'Rishikesh, India', ARRAY['Yoga', 'Spiritual', 'Fitness'], ARRAY['🧘‍♀️']),
    ('Radhika', 29, 'Female', 'Consultant. Solving problems. Let me solve yours.', 'Mumbai, India', ARRAY['Solving', 'Intellectual', 'Travel'], ARRAY['🧩']),
    ('Samaira', 22, 'Female', 'Fashion student. Designing the future. Style icon in making.', 'Delhi, India', ARRAY['Fashion', 'Design', 'Creative'], ARRAY['👠']),
    ('Shanaya', 25, 'Female', 'Actress aspiring. Drama on stage, not in life.', 'Mumbai, India', ARRAY['Acting', 'Creative', 'Chill'], ARRAY['🎭']),
    ('Siya', 26, 'Female', 'Software Dev. Debugging life. Want to be my co-pilot?', 'Bangalore, India', ARRAY['Techie', 'Coding', 'Gaming'], ARRAY['👩‍💻']),
    ('Tara', 23, 'Female', 'Travel Vlogger. Catch flights not feelings (maybe both).', 'Manali, India', ARRAY['Travel', 'Adventure', 'Video'], ARRAY['🏔️']),
    ('Urvi', 27, 'Female', 'Geologist. While you rock. I study rocks.', 'Jaipur, India', ARRAY['Science', 'Nature', 'Outdoors'], ARRAY['🪨']),
    ('Vedika', 24, 'Female', 'Teacher. Shaping minds. Tell me something I don''t know.', 'Pune, India', ARRAY['Teaching', 'Intellectual', 'Kids'], ARRAY['📚']),
    ('Yamini', 25, 'Female', 'Painter. Colors are my words. Paint with me.', 'Kolkata, India', ARRAY['Artistic', 'Painting', 'Quiet'], ARRAY['🖌️']),
    ('Zara', 22, 'Female', 'Model. Posing is work, chilling is life.', 'Mumbai, India', ARRAY['Fashion', 'Modeling', 'Fitness'], ARRAY['💅']),

    -- Male Personas (55 entries)
    ('Rohan', 26, 'Male', 'Startup founder. Sleep is optional, coffee is mandatory.', 'Bangalore, India', ARRAY['Entrepreneur', 'Techie', 'Ambition'], ARRAY['👨‍💻']),
    ('Arjun', 25, 'Male', 'Travel photographer. Living out of a backpack.', 'Mumbai, India', ARRAY['Travel', 'Photography', 'Adventurous'], ARRAY['📸']),
    ('Kabir', 27, 'Male', 'Chef. Express love through biryani. Good appetite?', 'Delhi, India', ARRAY['Foodie', 'Cooking', 'Chill'], ARRAY['👨‍🍳']),
    ('Vikram', 29, 'Male', 'Investment banker. Work hard, play hard. Cricket fan.', 'Mumbai, India', ARRAY['Ambitious', 'Sports', 'Luxury'], ARRAY['🏏']),
    ('Aditya', 24, 'Male', 'Musician. Guitar solos and late nights.', 'Pune, India', ARRAY['Music', 'Artistic', 'Romantic'], ARRAY['🎸']),
    ('Aryan', 23, 'Male', 'Fitness trainer. Health is wealth. Spot me?', 'Chandigarh, India', ARRAY['Fitness', 'Sports', 'Energy'], ARRAY['🏋️‍♂️']),
    ('Vihaan', 28, 'Male', 'Professor. Old bookstores & rainy days.', 'Kolkata, India', ARRAY['Intellectual', 'Reading', 'Deep Conversations'], ARRAY['📚']),
    ('Dhruv', 25, 'Male', 'Wildlife conservationist. Prefer animals to humans usually.', 'Dehradun, India', ARRAY['Nature', 'Animals', 'Adventurous'], ARRAY['🦁']),
    ('Aarav', 26, 'Male', 'Pilot. Catch me in the skies.', 'Delhi, India', ARRAY['Travel', 'Adventure', 'Flying'], ARRAY['✈️']),
    ('Vivaan', 24, 'Male', 'Game Developer. Building worlds. Player 1 ready.', 'Bangalore, India', ARRAY['Gaming', 'Techie', 'Creative'], ARRAY['🎮']),
    ('Sai', 27, 'Male', 'Civil Engineer. Building bridges (metaaphorically too).', 'Hyderabad, India', ARRAY['Engineering', 'Building', 'Chill'], ARRAY['🌉']),
    ('Reyansh', 22, 'Male', 'Student. Football fanatic. Forza!', 'Goa, India', ARRAY['Sports', 'Football', 'Energy'], ARRAY['⚽']),
    ('Krishna', 29, 'Male', 'Doctor. Healing hands. Long shifts but I make time.', 'Chennai, India', ARRAY['Health', 'Compassionate', 'Busy'], ARRAY['👨‍⚕️']),
    ('Ishaan', 25, 'Male', 'Stand-up comedian. I''ll make you laugh till it hurts.', 'Mumbai, India', ARRAY['Humor', 'Comedy', 'Social'], ARRAY['🎤']),
    ('Shaurya', 23, 'Male', 'Army cadet. Discipline & duty. Adventure seeker.', 'Pune, India', ARRAY['Fitness', 'Discipline', 'Patriotic'], ARRAY['🎖️']),
    ('Atharv', 26, 'Male', 'Architect. Designing the skyline.', 'Gurgaon, India', ARRAY['Design', 'Architecture', 'Creative'], ARRAY['🏙️']),
    ('Neel', 24, 'Male', 'Marine Biologist. The ocean is my home.', 'Andaman, India', ARRAY['Nature', 'Ocean', 'Science'], ARRAY['🌊']),
    ('Dev', 28, 'Male', 'Bartender. Mixing drinks & stories.', 'Bangalore, India', ARRAY['Social', 'Nightlife', 'Drinks'], ARRAY['🍹']),
    ('Rudra', 25, 'Male', 'Yoga teacher. Finding balance. Peace.', 'Rishikesh, India', ARRAY['Yoga', 'Spiritual', 'Chill'], ARRAY['🧘‍♂️']),
    ('Om', 30, 'Male', 'Spiritual guide. Meditation and mindfulness.', 'Varanasi, India', ARRAY['Spiritual', 'Meditation', 'Peace'], ARRAY['📿']),
    ('Ayaan', 23, 'Male', 'YouTuber. Vlogging my life. Be a guest star?', 'Mumbai, India', ARRAY['Video', 'Social Media', 'Creative'], ARRAY['📹']),
    ('Veer', 26, 'Male', 'Biker. Open roads and wind in my hair.', 'Ladakh, India', ARRAY['Biking', 'Travel', 'Adventurous'], ARRAY['🏍️']),
    ('Darsh', 24, 'Male', 'Animator. Bringing cartoons to life.', 'Pune, India', ARRAY['Artistic', 'Animation', 'Techie'], ARRAY['🎬']),
    ('Yash', 27, 'Male', 'Cricketer. Pitch is my playground.', 'Mumbai, India', ARRAY['Cricket', 'Sports', 'Fitness'], ARRAY['🏏']),
    ('Kian', 22, 'Male', 'DJ. Dropping beats. Let''s dance.', 'Goa, India', ARRAY['Music', 'Party', 'Nightlife'], ARRAY['🎧']),
    ('Shiv', 25, 'Male', 'Tattoo artist. Ink tells a story. What''s yours?', 'Delhi, India', ARRAY['Artistic', 'Tattoo', 'Creative'], ARRAY['💉']),
    ('Mohit', 28, 'Male', 'Product Manager. Roadmap to your heart?', 'Bangalore, India', ARRAY['Techie', 'Management', 'Ambition'], ARRAY['📈']),
    ('Laksh', 23, 'Male', 'Writer. Pen is mightier. Let me write a poem for you.', 'Lucknow, India', ARRAY['Writing', 'Poetry', 'Romantic'], ARRAY['✍️']),
    ('Manav', 26, 'Male', 'NGO Worker. Changing the world bit by bit.', 'Delhi, India', ARRAY['Activism', 'Kind', 'Social'], ARRAY['🌍']),
    ('Samarth', 29, 'Male', 'Lawyer. I win arguments. Try me.', 'Mumbai, India', ARRAY['Debate', 'Intellectual', 'Confidence'], ARRAY['⚖️']),
    ('Nakul', 24, 'Male', 'Botanist. I talk to plants.', 'Ooty, India', ARRAY['Nature', 'Plants', 'Quiet'], ARRAY['🌱']),
    ('Pranav', 25, 'Male', 'Robotics Engineer. Building the future.', 'Bangalore, India', ARRAY['Techie', 'Robotics', 'Science'], ARRAY['🤖']),
    ('Ranveer', 27, 'Male', 'Actor. Lights, camera, action.', 'Mumbai, India', ARRAY['Acting', 'Drama', 'Fitness'], ARRAY['🎭']),
    ('Varun', 23, 'Male', 'Surfer. Catching waves.', 'Pondicherry, India', ARRAY['Surfing', 'Beach', 'Fitness'], ARRAY['🏄‍♂️']),
    ('Sahil', 26, 'Male', 'Food Blogger. Eating my way through the city.', 'Delhi, India', ARRAY['Foodie', 'Social Media', 'Travel'], ARRAY['🍔']),
    ('Rishi', 28, 'Male', 'Astronomer. Stargazing dates?', 'Ladakh, India', ARRAY['Space', 'Science', 'Romantic'], ARRAY['🔭']),
    ('Akash', 24, 'Male', 'App Developer. There''s an app for that.', 'Hyderabad, India', ARRAY['Techie', 'Coding', 'Smart'], ARRAY['📲']),
    ('Ansh', 22, 'Male', 'Skater. Shredding the streets.', 'Pune, India', ARRAY['Skating', 'Cool', 'Outdoors'], ARRAY['🛹']),
    ('Jeet', 25, 'Male', 'Gym owner. Lifting spirits and weights.', 'Chandigarh, India', ARRAY['Fitness', 'Business', 'Strong'], ARRAY['🏋️']),
    ('Harsh', 27, 'Male', 'Journalist. Seeking the truth.', 'Debli, India', ARRAY['Writing', 'News', 'Intellectual'], ARRAY['📰']),
    ('Kunal', 29, 'Male', 'Banker. Safe with me.', 'Mumbai, India', ARRAY['Finance', 'Stable', 'Chill'], ARRAY['🏦']),
    ('Aadi', 23, 'Male', 'Graphic Designer. Visuals matter.', 'Bangalore, India', ARRAY['Design', 'Artistic', 'Creative'], ARRAY['🖊️']),
    ('Uday', 26, 'Male', 'Solar Engineer. Bright future ahead.', 'Jaipur, India', ARRAY['Engineering', 'Green', 'Techie'], ARRAY['☀️']),
    ('Zain', 24, 'Male', 'Model. Runway ready.', 'Delhi, India', ARRAY['Fashion', 'Modeling', 'Fitness'], ARRAY['🕺']),
    ('Ritvik', 25, 'Male', 'Podcaster. Let''s talk about it.', 'Mumbai, India', ARRAY['Talking', 'Media', 'Social'], ARRAY['🎙️']),
    ('Tanish', 22, 'Male', 'Student. Learning life.', 'Pune, India', ARRAY['Student', 'Fun', 'Young'], ARRAY['🎒']),
    ('Madhav', 28, 'Male', 'History Teacher. Learn from the past.', 'Agra, India', ARRAY['History', 'Teaching', 'Intellectual'], ARRAY['🏺']),
    ('Ehsaan', 30, 'Male', 'Composer. Harmony in chaos.', 'Chennai, India', ARRAY['Music', 'Composer', 'Artistic'], ARRAY['🎹']),
    ('Siddharth', 26, 'Male', 'Director. Calling the shots.', 'Mumbai, India', ARRAY['Film', 'Leadership', 'Creative'], ARRAY['🎬']);
